# Support the author by using the funding Links below
# Developed and maintained by Süha tanrıverdi with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/suhatanriverdi
# Buy Me a Coffee: https://buymeacoffee.com/suhatanriverdi

github: suhatanriverdi
buy_me_a_coffee: suhatanriverdi

# Your support means a lot to me to continue the development of open source project like this.